### ISSUE TITLE
LocationID parsing changes in 1.45 are parsing deviceID instead of location

### ISSUE THREAD

**Issue by cjkrolak** [csm10495/pyhtcc#13]
The changes made in 1.45 to enhance LocationID parsing are having unintended consequences.

result.url=https://mytotalconnectcomfort.com/portal/Device/Control/1457408

Control.Urls.refreshAlerts = '/portal/Device/Alerts?locationId=1357508&deviceId=1457408'

1.44 code was triggering ValueError because "portal" is not in the URL string, then it was correctly parsing LocationId from text.

1.45 code is now parsing the value at the end of the URL, which is my deviceID and assigning it to the LocationID.

I think we need to back to the 1.44 code since LocationId is not present in my URL.

**Comment by csm10495** [comment]
How many thermostats/locations do you have? Is it 1 thermostat in 1 location or more?

I'm trying to figure out some more heuristics here. It sounds like if you have 1 you redirect to the single device's page. (I think this is your case).

I have multiple so i redirect to a page listing the thermostats in my current location id. 

.. i wonder if there can even be multiple device ids for a single account.. In the meantime, while we ponder, i'll go back to the old logic.

**Comment by csm10495** [comment]
Oh geez.. so you can have multiple locations (and of course multiple devices under each location). If you have more than one it redirects you to: 'https://mytotalconnectcomfort.com/portal/Locations'

.. so that would mess up a lot of logic since the assumption is one location per pyhtcc object at the moment. 

Anyways I'm not going to attack the multi-location problem at this point. Maybe a future rewrite or if someone hits it. 

1.52.0 is out with the revert in place.

Thanks for reporting.

**Comment by cjkrolak** [comment]
thanks for the fast response.  I have one thermostat and one location
